// <auto-generated />
namespace IMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addedecnounter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedecnounter));
        
        string IMigrationMetadata.Id
        {
            get { return "202002271754247_added ecnounter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
